apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-updater
spec:
  selector:
    matchLabels:
      name: image-updater
  replicas: 1
  template:
    metadata:
      labels:
        name: image-updater
    spec:
      containers:
        - name: image-updater
          image: hhk14/nginx
          ports:
            - containerPort: 80
    
    
